services:
  postgres:
    image: postgres:latest
    container_name: yboost
    restart: always
    environment:
      - POSTGRES_USER=yboost
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=yboostdb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: